// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
///<reference types="node" />
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      process.env.NODE_ENV === "production"
        ? process.env.DATABASE_URL
        : process.env.NODE_ENV === "test"
          ? process.env.TEST_DATABASE_URL
          : process.env.NODE_ENV === "development"
            ? process.env.DEV_DATABASE_URL
            : process.env.DATABASE_URL,
  },
});
